/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-118501-ge18f87ed9f-20250219"
#endif /* AVUTIL_FFVERSION_H */
